-- Run this in Supabase SQL Editor
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS vip_level INTEGER DEFAULT 0;
ALTER TABLE withdrawals ADD COLUMN IF NOT EXISTS vat_amount REAL DEFAULT 0;
ALTER TABLE withdrawals ADD COLUMN IF NOT EXISTS credit_amount REAL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS referral_code TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS referred_by TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS reset_code TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS reset_expires TEXT DEFAULT '';

CREATE TABLE IF NOT EXISTS messages (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id),
  sender TEXT NOT NULL DEFAULT 'user',
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
